# Generated by Django 4.2.2 on 2024-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
